# Generated by Django 3.2.3 on 2021-08-06 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stages', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('option_1', models.CharField(max_length=150)),
                ('option_2', models.CharField(max_length=150)),
                ('option_3', models.CharField(blank=True, max_length=150, null=True)),
                ('option_4', models.CharField(blank=True, max_length=150, null=True)),
                ('answer', models.CharField(max_length=150)),
                ('stage', models.ForeignKey(default='#1', on_delete=django.db.models.deletion.CASCADE, to='quiz.stages')),
            ],
        ),
    ]
